<InSp>:
    BoxLayout:
        orientation: 'vertical'
        padding: 20
        spacing: 10
        Label:
            text: "Bienvenido al Gym App"
            font_size: 24

    # Box de Datos
    BoxLayout:
        orientation: 'vertical'
        size_hint_y: None
        height: 120
        spacing: 10

        TextInput:
            hint_text: "Escribe tu nombre aquÃƒÂ­"
            font_size: 18
            size_hint_y: None
            height: 40

        TextInput:
            hint_text: "ContraseÃƒÂ±a"
            password: True
            font_size: 18
            size_hint_y: None
            height: 40

    # Box de botones
    BoxLayout:
        orientation: 'horizontal'
        size_hint_y: None
        height: 40
        spacing: 10

        Button:
            text: 'Iniciar SesiÃƒÂ³n'
            font_size: 18
            size_hint_y: None
            height:
            on_release:
                app.root.current = 'pantalla3'

    # Texto con hipervÃƒÂ­nculo
    BoxLayout:
    Label:
        text: "[ref=registro]Ã‚Â¿No tienes cuenta? RegÃƒÂ­strate aquÃƒÂ­[/ref]"
        markup: True
        color: 0, 0, 1, 1
        font_size: 16
        on_ref_press:
            app.root.current = 'pantalla2'
